name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  default:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v16

      - name: Set up Cachix
        uses: cachix/cachix-action@v10
        with:
          name: danth
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build
        run: nix -L build .

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v16

      - name: Set up Cachix
        uses: cachix/cachix-action@v10
        with:
          name: danth
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          pushFilter: "electrode-clippy"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Clippy
        run: nix -L build .#checks.x86_64-linux.clippy
